version: "3.8"

services:

  # databases
  keycloak-db:
    container_name: keycloak-db
    image: postgres:16-alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # backends
  keycloak:
    container_name: keycloak
    build: .
    depends_on:
      - keycloak-db
    expose:
      - "80"
    command:
      - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
