version: "3.8"

services:

  # databases
  keycloak-db:
    container_name: keycloak-db
    image: postgres:16-alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d user -h localhost -p 5432
      interval: 10s
      timeout: 5s
      retries: 3

  # backends
  keycloak:
    container_name: keycloak
    build: .
    depends_on:
      - keycloak-db
    expose:
      - "80"
    command:
      - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  # dapr
  keycloak-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "user",
      "--app-port", "80",
      "--dapr-http-port", "3500",
      "-placement-host-address", "placement:50006",
      "--config", "/config.yaml",
      "--resources-path", "/components"
    ]
    network_mode: "service:keycloak"
volumes:
  keycloak-db-data:
